language: d

os:
  - linux
  - osx

install:
 - "./clean.sh"
 - "dub run --config=indexer --compiler=${DC}"

script:
 - "dub test glue-d:annotations -b unittest-cov --compiler=${DC}"
 - "dub test glue-d:logging -b unittest-cov --compiler=${DC}"
 - "dub test glue-d:utils -b unittest-cov --compiler=${DC}"
 - "dub test -b unittest-cov --compiler=${DC}"
after_success:
 - bash <(curl -s https://codecov.io/bash)

