language: d

##todo use some specific version of dmd/ldc, but also latest and nightly (this is gonna be a huge matrix)
jobs:
  include:
    - os: linux
      dist: xenial
      d: dmd
      env: CI_CONTEXT=xenial_dmd
    - os: linux
      dist: bionic
      d: dmd
      env: CI_CONTEXT=bionic_dmd
    - os: osx
      d: dmd
      env: CI_CONTEXT=osx_dmd
    - os: linux
      dist: xenial
      d: ldc
      env: CI_CONTEXT=xenial_ldc
    - os: linux
      dist: bionic
      d: ldc
      env: CI_CONTEXT=bionic_ldc
    - os: osx
      d: ldc
      env: CI_CONTEXT=osx_ldc

install:
 - ./clean.sh
 - "dub run --config=indexer --compiler=${DC}"

#todo in setups other than xenial/dmd there is no point in using -b unittest-cov
script:
 - "dub test glue-d:annotations -b unittest-cov --compiler=${DC}"
 - "dub test glue-d:logging -b unittest-cov --compiler=${DC}"
 - "dub test glue-d:utils -b unittest-cov --compiler=${DC}"
 - "dub test -b unittest-cov --compiler=${DC}"
after_success:
 # upload coverage only on linux/dmd (to minimize confusion)
 - '[ "$CI_CONTEXT" == "xenial_dmd" ] && bash <(curl -s https://codecov.io/bash)'

