language: d

os:
  - linux
  - osx

#todo use some specific version of each, but also latest and nightly (this is gonna be a huge matrix)
d:
  - dmd
  - ldc
  # GDC is explicitly not supported
  

install:
 - ./clean.sh
 - "dub run --config=indexer --compiler=${DC}"

script:
 - "dub test glue-d:annotations -b unittest-cov --compiler=${DC}"
 - "dub test glue-d:logging -b unittest-cov --compiler=${DC}"
 - "dub test glue-d:utils -b unittest-cov --compiler=${DC}"
 - "dub test -b unittest-cov --compiler=${DC}"
after_success:
 # upload coverage only on linux/dmd (to minimize confusion)
 - [ "$DC" == "dmd" && "$TRAVIS_OS_NAME" == "linux"] && bash <(curl -s https://codecov.io/bash)

